// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Storage.Contexts;

#nullable disable

namespace Storage.Migrations
{
    [DbContext(typeof(StorageContext))]
    [Migration("20231123102841_DataSeed")]
    partial class DataSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("Storage.Entities.Box", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PalletId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PalletId");

                    b.ToTable("Boxes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d595ce95-08ca-4a97-9e38-34a4717e99df"),
                            PalletId = new Guid("7cd4bde8-f707-45ec-bb68-d79bc592db26")
                        },
                        new
                        {
                            Id = new Guid("b1316bf2-e907-4192-bbd5-af2cab3e9bb3"),
                            PalletId = new Guid("5f8d3137-f994-426b-9868-3e3051ee10b4")
                        },
                        new
                        {
                            Id = new Guid("6ff2088d-9e5c-4043-9965-c1db84a19551"),
                            PalletId = new Guid("c341ac75-e415-4087-945f-f6c4f44d790f")
                        },
                        new
                        {
                            Id = new Guid("b5d201cf-a110-4cee-b318-4dcb7894d143"),
                            PalletId = new Guid("c341ac75-e415-4087-945f-f6c4f44d790f")
                        });
                });

            modelBuilder.Entity("Storage.Entities.Pallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pallets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7cd4bde8-f707-45ec-bb68-d79bc592db26")
                        },
                        new
                        {
                            Id = new Guid("5f8d3137-f994-426b-9868-3e3051ee10b4")
                        },
                        new
                        {
                            Id = new Guid("c341ac75-e415-4087-945f-f6c4f44d790f")
                        });
                });

            modelBuilder.Entity("Storage.Entities.Box", b =>
                {
                    b.HasOne("Storage.Entities.Pallet", null)
                        .WithMany("Boxes")
                        .HasForeignKey("PalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Storage.Entities.Pallet", b =>
                {
                    b.Navigation("Boxes");
                });
#pragma warning restore 612, 618
        }
    }
}
